spring.application.name=ai-startup-platform

spring.datasource.url=jdbc:mysql://localhost:3306/ai_startup_platform
spring.datasource.username=root
spring.datasource.password=Yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


gemini.api.key=gemini API key


server.port=8080